title: "Hyunseok Seung"
author: ""
description: "Postdoctoral Researcher, Statistics @ UWâ€“Madison."
remote_theme: jekyll/minima
url: "https://hseung88.github.io"

github_username: hseung88
linkedin_username: hseung

minima:
  skin: classic
  social_links:
    - { platform: email,
        user_url: "#",
        title: "hseung2 at wisc dot edu" }
    - { platform: google_scholar,
        user_url: "https://scholar.google.com/citations?user=qgzaJCcAAAAJ",
        title: "Google Scholar" }
    - { platform: linkedin,
        user_url: "https://www.linkedin.com/in/hseung/" }
    - { platform: github,
        user_url: "https://github.com/hseung88" }


plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

header_pages:
  - index.md
  - publications.md
  - cv.md
