title: "Hyunseok Seung"
tagline: "Postdoctoral Researcher, Statistics @ UW–Madison"
description: "Deep Learning Optimization · Bayesian Optimization"

url: "https://hseung88.github.io"
baseurl: ""

theme: jekyll-theme-chirpy

lang: en

timezone: America/Chicago

# Social links
social:
  github: hseung88
  linkedin: hseung
  google_scholar: "https://scholar.google.com/citations?user=qgzaJCcAAAAJ"
  email: "hseung2 at wisc dot edu"

# Navigation
nav:
  - title: Home
    url: /
  - title: Publications
    url: /publications
  - title: CV
    url: /cv

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

custom_css:
  - assets/css/custom-style.scss